services:
  api:
    container_name: api
    volumes:
      - ./api:/api
    build: .
    ports:
      - 8000:8000

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 5432:5432
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=realworld_db
      - MYSQL_USER=realworlduser
      - MYSQL_PASSWORD=realworldpassword
    command: ['--default-time-zone=+09:00']
    volumes:
      - ./docker/mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
